INSERT INTO country (continent, name) VALUES
('Europe', 'Macedonia'),
('Europe', 'Germany'),
('Europe', 'Italy'),
('Europe', 'France'),
('Europe', 'Spain'),
('Europe', 'Switzerland'),
('Asia', 'China'),
('Asia', 'Japan'),
('Asia', 'India'),
('America', 'United States'),
('America', 'Mexico'),
('America', 'Canada');

INSERT INTO author(name, surname, country_id) VALUES
('Author 1 Name', 'Author 1 Surname', 1),
('Author 2 Name', 'Author 2 Surname', 2),
('Author 3 Name', 'Author 3 Surname', 3),
('Author 4 Name', 'Author 4 Surname', 4),
('Author 5 Name', 'Author 5 Surname', 5),
('Author 6 Name', 'Author 6 Surname', 6),
('Author 7 Name', 'Author 7 Surname', 7),
('Author 8 Name', 'Author 8 Surname', 8),
('Author 9 Name', 'Author 9 Surname', 9),
('Author 10 Name', 'Author 10 Surname', 10),
('Author 11 Name', 'Author 11 Surname', 11),
('Author 12 Name', 'Author 12 Surname', 12),
('Author 13 Name', 'Author 13 Surname', 1),
('Author 14 Name', 'Author 14 Surname', 4),
('Author 15 Name', 'Author 15 Surname', 5),
('Author 16 Name', 'Author 16 Surname', 6),
('Author 17 Name', 'Author 17 Surname', 6),
('Author 18 Name', 'Author 18 Surname', 1),
('Author 19 Name', 'Author 19 Surname', 2),
('Author 20 Name', 'Author 20 Surname', 4);

INSERT INTO book(available_copies, category, name, author_id) VALUES
(4, 'NOVEL', 'Book 1', 1),
(7, 'THRILLER', 'Book 2', 2),
(8, 'HISTORY', 'Book 3', 3),
(7, 'FANTASY', 'Book 4', 4),
(2, 'BIOGRAPHY', 'Book 5', 5),
(1, 'CLASSICS', 'Book 6', 6),
(15, 'DRAMA', 'Book 7', 7),
(20, 'CLASSICS', 'Book 8', 8),
(14, 'NOVEL', 'Book 9', 9),
(5, 'NOVEL', 'Book 10', 10),
(4, 'NOVEL', 'Book 11', 11),
(3, 'CLASSICS', 'Book 12', 12),
(8, 'NOVEL', 'Book 13', 13),
(7, 'CLASSICS', 'Book 14', 14),
(6, 'NOVEL', 'Book 15', 15),
(5, 'HISTORY', 'Book 16', 16),
(4, 'DRAMA', 'Book 17', 17),
(2, 'HISTORY', 'Book 18', 18),
(9, 'BIOGRAPHY', 'Book 19', 1),
(1, 'HISTORY', 'Book 20', 1),
(2, 'DRAMA', 'Book 21', 2),
(3, 'HISTORY', 'Book 22', 3),
(5, 'NOVEL', 'Book 23', 2),
(4, 'FANTASY', 'Book 24', 4),
(4, 'FANTASY', 'Book 25', 18),
(7, 'CLASSICS', 'Book 26', 14),
(4, 'FANTASY', 'Book 27', 11),
(8, 'BIOGRAPHY', 'Book 28', 10);
